// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InitializeLibrary():Promise<void>;

export function LoadLibrary():Promise<void>;
