// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {uuid} from '../models';
import {main} from '../models';

export function GetFolder(arg1:uuid.UUID):Promise<main.FolderRef>;

export function GetFolderTree():Promise<main.FolderTreeNode>;

export function GetRootFolder():Promise<main.FolderRef>;

export function InitializeLibrary():Promise<void>;

export function LoadLibrary():Promise<void>;
