// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFolder(arg1) {
  return window['go']['main']['App']['GetFolder'](arg1);
}

export function GetFolderTree() {
  return window['go']['main']['App']['GetFolderTree']();
}

export function GetRootFolder() {
  return window['go']['main']['App']['GetRootFolder']();
}

export function InitializeLibrary() {
  return window['go']['main']['App']['InitializeLibrary']();
}

export function LoadLibrary() {
  return window['go']['main']['App']['LoadLibrary']();
}
