// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAbsPath(arg1) {
  return window['go']['main']['App']['GetAbsPath'](arg1);
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetAssetRef(arg1) {
  return window['go']['main']['App']['GetAssetRef'](arg1);
}

export function GetFolderRef(arg1) {
  return window['go']['main']['App']['GetFolderRef'](arg1);
}

export function GetFolderTree() {
  return window['go']['main']['App']['GetFolderTree']();
}

export function GetRootFolder() {
  return window['go']['main']['App']['GetRootFolder']();
}

export function InitializeLibrary() {
  return window['go']['main']['App']['InitializeLibrary']();
}

export function LoadLibrary() {
  return window['go']['main']['App']['LoadLibrary']();
}

export function ModifyAsset(arg1) {
  return window['go']['main']['App']['ModifyAsset'](arg1);
}

export function ModifyTag(arg1) {
  return window['go']['main']['App']['ModifyTag'](arg1);
}

export function ModifyTagsOfAsset(arg1, arg2, arg3) {
  return window['go']['main']['App']['ModifyTagsOfAsset'](arg1, arg2, arg3);
}
